colors:
  primary:
    backgroung: '#2f2828'
    foreground: '#ebdbb2'

    dim_foreground: '#828482'
    bright_foreground: '#eaeaea'

  cursor:
    text: CellBackground
    cursor: CellForeground

  selection:
    text: CellBackground
    background: CellForeground

  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#8bbb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'


